# Generated by Django 4.1 on 2024-04-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0005_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
