# Generated by Django 4.1 on 2024-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
