# Generated by Django 4.1.6 on 2023-06-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='brand',
        ),
    ]
